services:
  blog.api:
    image: ${DOCKER_REGISTRY-}blogapi
    build:
      context: .
      dockerfile: src/Blog.API/Dockerfile
    depends_on:
      - blog-db

  blog-db:
    image: postgres:16
    container_name: Blog.Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: medium_clone
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  blog-idp:
    image: quay.io/keycloak/keycloak:26.0
    container_name: Blog.Identity
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 18080:8080
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - keycloak_data:/opt/keycloak/data

volumes:
  postgres_data:
  keycloak_data:

